---
title: "Takım: Code or Die"
sidebar: false 
---

MUY660-İş Analitiği dersi takım sayfamıza hoş geldiniz.

Bu analitik çalışmalarımızı paylaşıyoruz.

Lütfen faaliyetlerimizi görmek için bizi takipte kalın.

## Takım Üyeleri

1.  [Safinaz Öksüz](/takim/safinazoksuz.qmd)

2.  [Betül Teke Sarıyer](/takim/betultekesariyer.qmd)

3.  [Hazal Akbulut Bıyık](/takim/hazalakbulutbiyik.qmd)

4.  [Oğuzhan Sarıyer](/takim/oguzhansariyer.qmd)

5.  [Gözde Tekin](/takim/gozdetekin.qmd)

6.  [Görkem Yalın](/takim/gorkemyalin.qmd)

7.  [Sait Fidan](/takim/saitfidan.qmd)

## Proje Adı

Türkiye'de 2013-2022 Yılları Arasında Gerçekleşen İntihar Vakalarının Cinsiyete ve Sebeplere Göre Bölgesel İncelenmesi

## Proje Konusu

Bu çalışmada, MUY660-İş Analitiği ders içeriğinin analitik yaklaşımlarını kullanarak Türkiye'de 2013-2022 yılları arasında gerçekleşen intihar vakalarının cinsiyete ve sebeplere göre bölgesel olarak incelenmesini hedefledik. Bu kapsamda, Türkiye genelindeki vakaları TÜİK araştırmalarından elde ederek çalışmanın verilerini derleyerek bir veri seti oluşturduk. Analiz sürecinde çeşitli yöntemler kullanarak detaylı çalışmalar gerçekleştirdik. Sonuç olarak, Türkiye'deki intihar vakalarını incelemeye yönelik bu çalışmanın, son 10 yılda gerçekleşen vakaları daha kapsamlı bir şekilde ele aldığını ve elde ettiğimiz bulguların önemli bir kaynak olduğunu belirledik.

## Veri Seti Hakkında Özet Bilgi

TÜİK araştırmalarından elde edilen verilerle toplamda 3 farklı veri seti oluşturduk. Bu veri setleri, 2013-2022 yılları arasında Türkiye genelinde toplam 9 farklı bölge ve metropol olan İstanbul'u ayrı incelediğimiz, toplamda 10 değişken içeren veri setlerini içermektedir. Bu veri setlerini ayrıca cinsiyet ayrımı yaparak 2 grupta inceledik. Son olarak, bu 10 yıl içindeki intiharların sebeplerini derlediğimiz bir veri seti oluşturduk:

1. 2013-2022 arası Türkiye'de intihar eden kadın sayısı
2. 2013-2022 arası Türkiye'de intihar eden erkek sayısı
3. 2013-2022 arası Türkiye'de intihar eden kişilerin intihar sebepleri

## Sonuçlar

Burada key takeways verilmelidir. En az 3 en fazla 5 madde ile çarpıcı sonuçlar sunulmalıdır.
